# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1989be0ed03de578e32e8a2d671fa8e23417c5ce388833b601170cabcd6d6898732b772b31490d6332dc88eb253ff3e950375761996d0275155dda4b0dfd30e4

test:
  secret_key_base: dee02d256bf7b1a18ef31cac7f14b217f58697c0942777ba2a6cc6005156b98258dfba869b38dd896b6e578d456513c1f15fdafde6dc04d9d51e2e35a9e246cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
